### ISSUE TITLE
getTimeZone Warning in  React Native 0.57  

### ISSUE THREAD

**Issue by ElangoPrince** [samitha9125/react-native-timezone#1]
### **RN 0.57 Error**
`undefined is not an object (evaluating '_reactNativeTimezone.default.getTimeZone')`

> const timeZone **=** await TimeZone.getTimeZone().then(zone => zone);

**Comment by samitha9125** [comment]
Please attach the code parts mentioning how you imported the library and used it to get the timezone.

**Comment by ElangoPrince** [comment]
```
import TimeZone from 'react-native-timezone';
async componentDidMount(){
  const timeZone = await TimeZone.getTimeZone().then(zone => zone);
}
```

**Comment by samitha9125** [comment]
Can you also mention your react-native complete version (0.57.x) and in what platform this error occurs?

**Comment by samitha9125** [comment]
@ElangoPrince Please do `react-native link react-native-timezone` after installation before running the app. Please refer Readme. I tested this and since this is working, I'm closing this issue. Thank you for using this library.

**Comment by ElangoPrince** [comment]
@samitha9125  okay thanks , i'll check.
