### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by RamProg** [samitha9125/react-native-timezone#2]
Just to let you know I had to use --force to install this

Error log:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: XXXXX@0.0.1
npm ERR! Found: react-native@0.64.0
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.64.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.41.2" from react-native-timezone@1.0.3
npm ERR! node_modules/react-native-timezone
npm ERR!   react-native-timezone@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/XXXXX/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/XXXX/.npm/_logs/2021-06-14T15_42_38_227Z-debug.log

**Comment by samitha9125** [comment]
@RamProg Fixed in version 2.0.0. Since this is fixed now, I'm closing this issue.
