### ISSUE TITLE
Android not working

### ISSUE THREAD

**Issue by jamieGardyn** [samitha9125/react-native-timezone#4]
Getting this error when using in Android...

TypeError: null is not an object (evaluating '_reactNativeTimezone.default.getTimeZone')

**Comment by samitha9125** [comment]
@jamieGardyn Can you mention your RN version?

**Comment by jamieGardyn** [comment]
> @jamieGardyn Can you mention your RN version?

0.63.4

**Comment by jamieGardyn** [comment]
Looks like it wasn't linked upon install in Android, as react-native-timezone is not found in settings.gradle or app/src/build.gradle - manually added it in both spots like below, but that didn't fix the issue, so not sure...

to build.gradle, added...
implementation project(':react-native-timezone')

to settings.gradle added:
include ':react-native-timezone'
project(':react-native-timezone').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-timezone/android')

**Comment by samithaFHSS** [comment]
Sorry for the late reply. This is not necessary for releases after 0.60 since it supports auto-linking.

**Comment by jamieGardyn** [comment]
> Sorry for the late reply. This is not necessary for releases after 0.60 since it supports auto-linking.

But when you autolink, isn't it supposed to add these lines for you automatically? So those lines should exist if I look at that file, right?

**Comment by Yuniac** [comment]
This package still does not work, you can't even install it. Even after adding the lines mentioned above manually to `build.gradle` and `settings.gradle` and trying (as mentioned in another issue) `react-native link react-native-timezone` you still can't use it because it's null

**Comment by samitha9125** [comment]
Timezone 2.1.0 is released now and it is compatible with all major react native versions. Tested as well. Thus, I'm closing this issue. Please feel free to reopen if you face the same issue.
