### ISSUE TITLE
Fixed: A problem occurred evaluating project ':react-native-timezone' with react-native v0.70.1

### ISSUE THREAD

**Issue by ajaykumar97** [samitha9125/react-native-timezone#6]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

I have created a patch to fix this compilation issue using [patch-package](https://github.com/ds300/patch-package) to patch `react-native-timezone@2.0.0`.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-timezone/android/build.gradle b/node_modules/react-native-timezone/android/build.gradle
index a28f0dd..59d8ab5 100644
--- a/node_modules/react-native-timezone/android/build.gradle
+++ b/node_modules/react-native-timezone/android/build.gradle
@@ -31,6 +31,6 @@ repositories {
 }
 
 dependencies {
-    compile 'com.facebook.react:react-native:+'
+    implementation 'com.facebook.react:react-native:+'
 }
   
\ No newline at end of file
```
To use above patch, create a file under the file path `patches/react-native-timezone+2.0.0.patch` (create a patch folder at root level if you do not have it already) and paste the above code block inside it. Then run `npx patch-package`. It will apply the above patch. The build should run successfully now.

**Comment by natemartins** [comment]
Which root level? Root level of the package, root level of android folder, or root level of the project?

**Comment by r0b0t3d** [comment]
@ajaykumar97 can you please create PR for it?

**Comment by samitha9125** [comment]
Timezone 2.1.0 is released now and it is compatible with all major react native versions. Tested as well. Thus, I'm closing this issue. Please feel free to reopen if you face the same issue.
